name: motor_flutter
description: The Sonr Motor Plugin for Flutter
version: 0.0.1
homepage: https://sonr.io

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  alan: ^0.40.2+1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.sonr.motor_flutter
        pluginClass: MotorFlutterPlugin
      ios:
        pluginClass: MotorFlutterPlugin
